# config/profiles/simulation.py

# Identity
ROBOT_ID = "sim"
ENVIRONMENT = "simulation"
SURFACE = "simulation"

# Drive hardware
DRIVE_LAYOUT = "2WD"
WHEEL_TYPE = "standard"
MOTOR_POLARITY = [1, 1]
MOTION_BACKEND = "timed"

# Base calibration
BASE_ROTATE_FACTOR = 1.0
BASE_DRIVE_FACTOR = 1.0

SURFACE_MULTIPLIERS = {
    "simulation": {"rotate": 1.00, "drive": 1.00},
}

# Grabbing
GRAB_DISTANCE_MM = 140.0

# InitEscape
INIT_ESCAPE_DRIVE_MM = 200
INIT_ESCAPE_ROTATE_DEG = 25.0

# PostPickupRealign
POST_PICKUP_REVERSE_MM = 120
POST_PICKUP_ROTATE_DEG = 180.0

# RecoverLocalisation
RECOVER_STEP_DEG = 15.0
RECOVER_MAX_SWEEP_DEG = 180.0
RECOVER_SETTLE_TIME = 0.25

# Motion limits
MIN_ROTATE_DEG = 2.0
MAX_ROTATE_DEG = 90.0
MIN_DRIVE_MM = 5.0
MAX_DRIVE_MM = 550.0
MAX_MOTOR_POWER = 0.8

# Vision / perception
CAMERA_SETTLE_TIME = 0.5
MARKER_HEIGHT_MAX_DISTANCE_MM = 1000
MARKER_PITCH_HIGH_DEG = 0.35
MARKER_PITCH_LOW_DEG = 0.10
FINAL_COMMIT_DISTANCE_MM = 500
VISION_LOSS_TIMEOUT_S = 1.5


