from enum import Enum, auto

class RobotState(Enum):
    SCRIPTED_START = auto()
    INIT_ESCAPE = auto()
    PREPARE_SEARCH = auto()
    GLOBAL_OBJECT_SEARCH = auto()
    SELECT_TARGET = auto()
    APPROACH_OBJECT = auto()
    PICKUP_OBJECT = auto()
    SEEK_AND_COLLECT = auto()
    POST_PICKUP_REALIGN = auto()
    RECOVER_LOCALISATION = auto()
    RETURN_TO_BASE = auto()
    STACK_OBJECT = auto()
    DROPOFF_OBJECT = auto()
    POST_DROPOFF_REALIGN = auto()
    REACQUIRE_TARGET = auto()
    BACKOFF_SCAN = auto()
    ROTATE_AND_DRIVE = auto()
    COMPLETE = auto()
